name: nlp
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - ca-certificates=2020.1.1=0
  - certifi=2020.6.20=py37_0
  - intel-openmp=2020.1=217
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20191231=h7b6447c_0
  - libffi=3.3=he6710b0_1
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - mkl=2020.1=217
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.1.0=py37h23d657b_0
  - mkl_random=1.1.1=py37h0573a6f_0
  - ncurses=6.2=he6710b0_1
  - numpy=1.18.5=py37ha1c710e_0
  - numpy-base=1.18.5=py37hde5b4d6_0
  - openssl=1.1.1g=h7b6447c_0
  - pip=20.1.1=py37_1
  - python=3.7.7=hcff3b4d_5
  - readline=8.0=h7b6447c_0
  - scikit-learn=0.20.3=py37hd81dba3_0
  - scipy=1.5.0=py37h0b6359f_0
  - setuptools=47.3.1=py37_0
  - six=1.15.0=py_0
  - sqlite=3.32.3=h62c20be_0
  - tk=8.6.10=hbc83047_0
  - wheel=0.34.2=py37_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - absl-py==0.9.0
    - annoy==1.16.3
    - astunparse==1.6.3
    - blis==0.4.1
    - boto==2.49.0
    - boto3==1.14.14
    - botocore==1.17.14
    - cachetools==4.1.1
    - catalogue==1.0.0
    - chardet==3.0.4
    - click==7.1.2
    - cycler==0.10.0
    - cymem==2.0.3
    - cytoolz==0.10.1
    - dask==2.19.0
    - decorator==4.4.2
    - dill==0.3.2
    - docutils==0.15.2
    - en-core-web-sm==2.3.0
    - ftfy==4.4.3
    - gast==0.3.3
    - gensim==3.8.3
    - google-auth==1.18.0
    - google-auth-oauthlib==0.4.1
    - google-pasta==0.2.0
    - grpcio==1.30.0
    - h5py==2.10.0
    - html5lib==1.1
    - idna==2.10
    - ijson==3.1.post0
    - importlib-metadata==1.7.0
    - jmespath==0.10.0
    - joblib==0.15.1
    - keras==2.2.4
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.2
    - kiwisolver==1.2.0
    - ktext==0.40
    - markdown==3.2.2
    - matplotlib==3.2.2
    - more-itertools==8.4.0
    - msgpack==1.0.0
    - msgpack-numpy==0.4.6.post0
    - multiprocess==0.70.10
    - murmurhash==1.0.2
    - networkx==2.4
    - nltk==3.5
    - oauthlib==3.1.0
    - opt-einsum==3.2.1
    - pandas==1.0.5
    - pathos==0.2.6
    - plac==1.1.3
    - pox==0.2.8
    - ppft==1.6.6.2
    - preshed==3.0.2
    - protobuf==3.12.2
    - pyarrow==0.17.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyemd==0.5.1
    - pyparsing==2.4.7
    - pyphen==0.9.5
    - python-dateutil==2.8.1
    - python-levenshtein==0.12.0
    - pytz==2020.1
    - pyyaml==5.3.1
    - regex==2020.6.8
    - requests==2.24.0
    - requests-oauthlib==1.3.0
    - rsa==4.6
    - s3transfer==0.3.3
    - smart-open==2.1.0
    - spacy==2.3.0
    - srsly==1.0.2
    - tensorboard==2.2.2
    - tensorboard-plugin-wit==1.7.0
    - tensorflow==2.2.0
    - tensorflow-estimator==2.2.0
    - termcolor==1.1.0
    - textacy==0.6.2
    - thinc==7.4.1
    - toolz==0.10.0
    - tqdm==4.47.0
    - unidecode==1.1.1
    - urllib3==1.25.9
    - wasabi==0.7.0
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - werkzeug==1.0.1
    - wrapt==1.12.1
    - zipp==3.1.0
prefix: /home/y2587wan/miniconda3/envs/nlp

